config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users

  resources :projects do
    resources :media
    get 'media/:id/cancel', to: 'media#cancel', as: :medium_cancel
  end

  get 'users', to: 'users#index', as: :users
  get 'users/:id/promote', to: 'users#promote', as: :promote
  get 'users/:id/demote', to: 'users#demote', as: :demote
  get 'projects/:id/change-status', to: 'projects#change_status', as: :project_change_status
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% if type == "notice" %>
    <div><%= message %></div> 
  <% end %>
  <% if type == "alert" %>
    <div><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer>
Footer :

  <% if current_user %>

    <p>Username : <%= current_user.username.humanize %></p>
    <p>You are : [<%= current_user.role %>]</p>

    <div>
      <%= link_to 'Edit Profile', edit_user_registration_path %>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    </div>
  <% else %>
    <div>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    </div>
  <% end %>

  <div>
    <%= link_to "Users admin panel", users_path if current_user&.staff? %>
  </div>
</footer>

app/views/layouts/shared/_form_error.html.erb
<% if object.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object %> from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<header>
Header : 
<%= link_to "Home", root_path %>
<%= link_to "Projects", projects_path %>
</header>