config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users

  resources :projects do
    resources :media
    get 'media/:id/cancel', to: 'media#cancel', as: :medium_cancel
  end

  get 'users', to: 'users#index', as: :users
  get 'users/:id/promote', to: 'users#promote', as: :promote
  get 'users/:id/demote', to: 'users#demote', as: :demote
  get 'projects/:id/change-status', to: 'projects#change_status', as: :project_change_status
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  # Relationships
  
  has_many :media, dependent: :destroy
  belongs_to :user

  # Friendly Id sluggable

  extend FriendlyId
  friendly_id :title, use: :slugged

  # Validations 

  validates :title, :category, :status, :user_id, presence: true
  validates :title, :slug, uniqueness: true

  # Enums

  enum category: [:documentary, :institutional, :event]
  enum status: [:unpublished, :published]

  # Scopes

  scope :filter_by_status, ->(status) { where(status: status) }
  scope :filter_by_title, ->(title) { where("title ILIKE ?", "%#{title}%") }
  scope :filter_by_category, ->(category) { where(category: category) }

  # Actions

  # Turbo_stream

  after_update_commit do
    broadcast_update_to self, partial: "projects/partials/project", locals: { project: self }
    broadcast_remove_to self if self.status === "unpublished"
  end

  after_destroy_commit do
    broadcast_remove_to self
  end

  # Custom entity Methods

  def change_status!
    if self.status == "unpublished"
      self.status = "published"
    else
      self.status = "unpublished"
    end
  end

  private

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include RecordHelper
  include ActionView::RecordIdentifier
  
  before_action :authenticate_user!, only: %i[ new edit create update destroy change_status ]
  before_action :set_project, only: %i[ show edit update destroy change_status ]

  # GET /projects
  def index
    @projects = policy_scope(Project).order(date: :desc)
    @projects = @projects.filter_by_title(params[:title]) if params[:title].present?  
    @projects = @projects.filter_by_category(params[:category]) if params[:category].present?  
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    # Set active user as project owner
    @project.user = current_user

    authorize @project
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    # Set active user as project owner
    @project.user = current_user

    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      else
        format.html { render :destroy, status: :unprocessable_entity }
      end
    end
  end

  def change_status
    @project.change_status!

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project's status was successfully changed." }
      else
        format.html { render :project, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = policy_scope(Project).friendly.find(params[:id])
      authorize @project
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :slug, :subject, :category, :description, :location, :date, :status, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<article id="<%= dom_id(project) %>">
  Title : <%= project.title.humanize %><br/>
  Subject : <%= project.subject %><br/>
  Category : <%= project.category.humanize %><br/>
  Description : <%= project.description %><br/>
  Location : <%= project.location %><br/>
  Date : <%= project.date %><br/>
  Published_state : <%= project.status %><br/>
  Posted by : <%= project.user.username %>, <%= project.user.email.humanize %><br/>
</article>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render partial: "projects/partials/form", locals: { project: @project } %>

app/views/projects/index.html.erb
<h1>Project#Index</h1>

<h2>Query form</h2>

<%= form_tag projects_path, method: :get, data: { turbo_frame: "projects-filter-results", turbo_action: "advance", controller: "filter", action: "input->filter#submit" } do |f| %>
  <%= text_field_tag "title", nil, placeholder: "Search ..." %>
  <%= select_tag "category", options_from_collection_for_select(Project.categories.keys, :to_s, :titlecase), include_blank: true, default: 0 %>
  <%= submit_tag "Search" %>
<% end %>

<h2>Projects</h2>

<%= turbo_frame_tag "projects-filter-results" do %>
  <%= render partial: "projects/partials/projects", locals: { projects: @projects } %>
<% end %>

<% if current_user&.staff? %>
  <div>
    <%= link_to "New project", new_project_path %>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render partial: "projects/partials/form", locals: { project: @project } %>

app/views/projects/show.html.erb
<h1>Project#Show</h2>

<h2>Project info</h2>

<%= render partial: "projects/partials/project", locals: { project: @project } %>

<% if current_user&.staff? %>
  <div>
    <%= link_to "#{@project.published? ? "Unpublish" : "Publish"}", project_change_status_path(@project) %>
    <%= link_to "Edit project", edit_project_path(@project) %>
    <%= button_to "Delete project", project_path(@project), method: :delete %>
  </div>
<% end %>

<!-- Media form -->
<% if current_user&.staff? %>

  <h2>Media form</h2>

  <%= render partial: "media/partials/form", locals: { medium: Medium.new, project: @project } %>
<% end %>

<h2>Project's media</h2>

<%= turbo_stream_from @project, :media %>
<%= tag.div id: "#{dom_id(@project)}_media" do %>
  <%= render partial: "media/partials/medium", collection: policy_scope(@project.media) %>
<% end %>