config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users

  resources :projects do
    resources :media
    get 'media/:id/cancel', to: 'media#cancel', as: :medium_cancel
  end

  get 'users', to: 'users#index', as: :users
  get 'users/:id/promote', to: 'users#promote', as: :promote
  get 'users/:id/demote', to: 'users#demote', as: :demote
  get 'projects/:id/change-status', to: 'projects#change_status', as: :project_change_status
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  include ActionView::RecordIdentifier
  include RecordHelper

  before_action :set_medium, only: %i[ show edit update destroy ]
  before_action :set_project, only: %i[ new edit create update destroy cancel ]
  
  # GET /media/1
  def show
  end

  # GET /media/1/edit
  def edit
  end

  # GET /media/new
  def new
    @medium = Medium.new
    # Set active user as project owner
    @medium.project = @project

    authorize @medium
  end

  # POST projects/:id/media
  def create
    @medium = @project.media.new(medium_params)
    authorize @medium

    respond_to do |format|
      if @medium.save
        medium = Medium.new
        format.turbo_stream { render turbo_stream: turbo_stream.update("#{dom_id(@project)}_media", partial: "media/partials/medium", collection: policy_scope(@project.media)) }
        format.html { redirect_to project_path(@project), notice: "Medium successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.turbo_stream { render turbo_stream: turbo_stream.update("#{dom_id(@medium.project)}_media", partial: "media/partials/medium", collection: policy_scope(@project.media)) }
        format.html { redirect_to project_path(@medium.project), notice: "Medium successfully updated."  }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  def destroy
    respond_to do |format|
      if @medium.destroy
        format.turbo_stream { render turbo_stream: turbo_stream.update("#{dom_id(@medium.project)}_media", partial: "media/partials/medium", collection: policy_scope(@project.media)) } 
        format.html { redirect_to project_path(@medium.project), notice: "Medium successfully destroyed."  }
      else
        format.html { render :destroy, status: :unprocessable_entity }        
      end
    end
  end

  def cancel
    respond_to do |format|
      if @project
        format.turbo_stream { render turbo_stream: turbo_stream.update("#{dom_id(@medium.project)}_media", partial: "media/partials/medium", collection: policy_scope(@project.media)) }
        format.html { redirect_to project_path(@project), notice: "Medium edit cancelled" }
      else
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  private

  def medium_params
    params.require(:medium).permit(:title, :description, :author, :location, :visual_url, :date, :priority_index, :project_id, :visual)
  end

  def set_medium
    @medium = policy_scope(Medium).find(params[:id])
    authorize @medium
  end

  def set_project
    @project = policy_scope(Project).friendly.find(params[:project_id])
    authorize @project
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/partials/_form-fields.html.erb
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :author %>
  <%= form.text_field :author %>
</div>

<div>
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div>
  <%= form.label :location %>
  <%= form.text_field :location %>
</div>

<div>
  <%= form.label :date %>
  <%= form.date_field :date %>
</div>

<div>
  <div>
    <%= form.label :visual_url %>
    <%= form.text_field :visual_url, data: { action: "new-medium-form-manager#onTextFieldUpdate", "new-medium-form-manager-target": "textField" } %>
  </div>

  <div>
    <%= form.label :visual %>
    <%= form.file_field :visual, accept: "image/png, image/jpeg, image/jpg", data: { action: "new-medium-form-manager#onFileFieldUpdate", "new-medium-form-manager-target": "fileField" } %>
    <%= submit_tag "Remove", type: "button", style: "display:none", data: { "new-medium-form-manager-target": "fileCancelButton" } %>
  </div>

  <% if form.object.visual.attached? %>
    <%= image_tag url_for(form.object.visual), id: 'medium-contained-img', data: { "new-medium-form-manager-target": "preview" }, style: "display:block" %>
  <% else %>
    <%= image_tag '', data: { "new-medium-form-manager-target": "preview" }, style: "display:none" %>
  <% end %>
</div>

<div>
  <%= form.label :priority_index %>
  <%= form.select :priority_index, options_for_select(1..100) %>
</div>

<div>
  <%= form.submit %>
</div>

app/views/media/partials/_form.html.erb
<% model = [local_assigns[:project], medium].compact %>

<%# debugger %>

<%= turbo_frame_tag medium do %>
  <%= form_with model: model, data: { controller: "new-medium-form-manager", action: "turbo:submit-end->new-medium-form-manager#reset" } do |form| %>
    <%= render "layouts/shared/form_error", object: medium %>
    <%= render "media/partials/form-fields", form: form %>
    <% if medium.id %>
      <%= link_to 'Cancel', project_medium_cancel_path(project, medium) %>
    <% end %>
  <% end %>
<% end %>

app/views/media/partials/_medium.html.erb
<%= turbo_stream_from medium %>
<%= turbo_frame_tag medium do %>

  <div id="<%= dom_id(medium)%>">
    Title : <%= medium.title %>
    Description : <%= medium.description %>
    Author : <%= medium.author %>
    Location : <%= medium.location %>
    Date : <%= medium.date %>
    priority_index : <%= medium.priority_index %>
    
    <% if medium.visual.attached? %>
      <%= image_tag url_for(medium.visual) %>
    <% elsif medium.visual_url? %>
      <%= get_video_iframe(medium.visual_url) %>
    <% end %>

    <% if current_user&.staff? %>
      <div>
        <%= link_to "Edit", edit_project_medium_path(medium.project, medium) %>
        <%= button_to  "Delete", project_medium_path(medium.project, medium), method: :delete %>
      </div>
    <% end %>

  </div>

<% end %>